name: Github WorkFlows CICD

on: 
    push: 
        branches: 
            - main

jobs:
    build-frontend-and-node-api:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                  - context: ./fontend
                    image_name: ghcr.io/ismail-mouyahada/cicd-projet-docker/frontend:latest
                  - context: ./node-api
                    image_name: ghcr.io/ismail-mouyahada/cicd-projet-docker/node-api:latest
        permissions:
            packages: write
        steps:
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            - 
                name: Checkout 
                uses: actions/checkout@v3

            -
                name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: ${{ matrix.image_name}}
            - 
                name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v5
                with:
                    context: ${{ matrix.context }}
                    push: true
                    tags: ${{ matrix.image_name }}
                    cache-from: type=gha
                    cache-to: type=gha, mode=max